### ISSUE TITLE
Possible bug with comparing strings

### ISSUE THREAD

**Issue by hhaslam11** [BrendonButler/Visionless#5]
Didn't really do much (or any) testing, but just from browsing through your code I found something that could potentially be problematic. 

On line [45 of Battle.java](https://github.com/BrendonButler/Visionless/blob/master/src/net/sparkzz/visionless/game/Battle.java#L45) you compare a string, `lastAttacks` using `==`, this won't work. You need to use  `.equals()` when comparing strings. 

try  `if (!lastAttacks.equals(""))` instead :)

**Comment by hhaslam11** [comment]
see [http://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java](http://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java)

**Comment by BrendonButler** [comment]
@hhaslam11 Thanks! Generally I don't do that. It was probably one of my 2 am nights, haha. Thanks though!
